ArchiNestCoreMVCProject/Controllers/AdminServiceController.cs
using ArchiNestCoreMVCProject.Context;
using ArchiNestCoreMVCProject.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ArchiNestCoreMVCProject.Controllers
{
    public class AdminServiceController : Controller
    {
        private readonly DatabaseContext _context;

        public AdminServiceController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var values = _context.Services.ToList();
            return View(values);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Services newService)
        {
            _context.Services.Add(newService);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var value = _context.Services.Find(id);
            _context.Services.Remove(value);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var value = _context.Services.Find(id);
            return View(value);
        }

        [HttpPost]
        public IActionResult Update(Services updatedService)
        {
            _context.Services.Update(updatedService);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ArchiNestCoreMVCProject/Views/AdminService/Add.cshtml
@model ArchiNestCoreMVCProject.Entities.Services
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Add New Service</h4>
            <form class="forms-sample" method="post" asp-action="Add" asp-controller="AdminService">

                <div class="form-group">
                    <label>Title</label>
                    <input type="text" class="form-control" placeholder="Title" asp-for="Title">
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <input type="text" class="form-control" placeholder="Description" asp-for="Description">
                </div>

                <div class="form-group">
                    <label>Image URL</label>
                    <input type="text" class="form-control" placeholder="Image URL" asp-for="ImageUrl">
                </div>

                <button type="submit" class="btn btn-primary me-2">Add</button>
            </form>
        </div>
    </div>
</div>

ArchiNestCoreMVCProject/Views/AdminService/Index.cshtml
@model List<ArchiNestCoreMVCProject.Entities.Services>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
	<div class="card">
		<div class="card-body">
			<h4 class="card-title">Services</h4>
			<div class="table-responsive">
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>#</th>
							<th>Title</th>
							<th>Description</th>
							<th>Image URL</th>
							<th>Operations</th>
						</tr>
					</thead>
					<tbody>
						@foreach(var item in Model){
							<tr>
								<td>@item.ServicesId</td>
								<td>@item.Title</td>
								<td>@item.Description.Substring(0, 20)...</td>
								<td align="center"><img src="@item.ImageUrl" style="height:61px; width:69px;" /></td>
								<td>
									<a type="button" class="btn btn-inverse-primary btn-fw" href="/AdminService/Update/@item.ServicesId">Update</a>
									&nbsp;
									<a type="button" class="btn btn-inverse-danger btn-fw" href="/AdminService/Delete/@item.ServicesId">Delete</a>
								</td>
							</tr>
						}
						
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

ArchiNestCoreMVCProject/Views/AdminService/Update.cshtml
@model ArchiNestCoreMVCProject.Entities.Services
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}


<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update Service Page</h4>
            <form class="forms-sample" method="post" asp-action="Update" asp-controller="AdminService">

                <input type="hidden" asp-for="ServicesId" class="form-control" />

                <div class="form-group">
                    <label>Title</label>
                    <input type="text" class="form-control" placeholder="Title" asp-for="Title">
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <input type="text" class="form-control" placeholder="Description" asp-for="Description">
                </div>

                <div class="form-group">
                    <label>Image URL</label>
                    <input type="text" class="form-control" placeholder="Image URL" asp-for="ImageUrl">
                </div>

                <button type="submit" class="btn btn-primary me-2">Update</button>
            </form>
        </div>
    </div>
</div>