ArchiNestCoreMVCProject/Controllers/AdminHomeController.cs
using ArchiNestCoreMVCProject.Context;
using ArchiNestCoreMVCProject.Entities;
using Microsoft.AspNetCore.Mvc;

namespace ArchiNestCoreMVCProject.Controllers
{
    public class AdminHomeController : Controller
    {
        private readonly DatabaseContext _context;

        public AdminHomeController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var values = _context.Homes.ToList();
            return View(values);
        }

        public IActionResult Delete(int id)
        {
            var value = _context.Homes.Find(id);
            _context.Homes.Remove(value);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var value = _context.Homes.Find(id);
            return View(value);
        }

        [HttpPost]
        public IActionResult Update(Home updatedHome)
        {
            _context.Homes.Update(updatedHome);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ArchiNestCoreMVCProject/Views/AdminHome/Index.cshtml
@model List<ArchiNestCoreMVCProject.Entities.Home>
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/AdminLayout/Index.cshtml";
}


<div class="col-lg-12 grid-margin stretch-card">
	<div class="card">
		<div class="card-body">
			<h4 class="card-title">Home</h4>
			<div class="table-responsive">
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>#</th>
							<th>Title</th>
							<th>Subtitle</th>
							<th>Operations</th>
						</tr>
					</thead>
					<tbody>

						@foreach (var item in Model)
						{
							<tr>
								<td>@item.HomeId</td>
								<td>@item.Title</td>
								<td>@item.Subtitle.Substring(0,50)...</td>
								<td>
									<a type="button" class="btn btn-inverse-primary btn-fw" href="/AdminHome/Update/@item.HomeId">Update</a>
									&nbsp;
									<a type="button" class="btn btn-inverse-danger btn-fw" href="/AdminHome/Delete/@item.HomeId">Delete</a>
								</td>
							</tr>
						}
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

ArchiNestCoreMVCProject/Views/AdminHome/Update.cshtml
@model ArchiNestCoreMVCProject.Entities.Home
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}


<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update Home Page</h4>
            <form class="forms-sample" method="post" asp-action="Update" asp-controller="AdminHome">

                <input type="hidden" asp-for="HomeId" class="form-control" />

                <div class="form-group">
                    <label>Title</label>
                    <input type="text" class="form-control" placeholder="Title" asp-for="Title">
                </div>
                <div class="form-group">
                    <label>Subtitle</label>
                    <input type="text" class="form-control" placeholder="Subtitle" asp-for="Subtitle">
                </div>
               
                <button type="submit" class="btn btn-primary me-2">Update</button>
            </form>
        </div>
    </div>
</div>