ArchiNestCoreMVCProject/Controllers/AdminAboutController.cs
using ArchiNestCoreMVCProject.Context;
using ArchiNestCoreMVCProject.Entities;
using Microsoft.AspNetCore.Mvc;

namespace ArchiNestCoreMVCProject.Controllers
{
    public class AdminAboutController : Controller
    {
        private DatabaseContext _context;

        public AdminAboutController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var values = _context.Abouts.FirstOrDefault();
            return View(values);
        }

        public IActionResult Delete(int id)
        {
            var value = _context.Abouts.Find(id);
            _context.Abouts.Remove(value);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var value = _context.Abouts.Find(id);
            return View(value);
        }

        [HttpPost]
        public IActionResult Update(About updatedAbout)
        {
            _context.Abouts.Update(updatedAbout);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

ArchiNestCoreMVCProject/Views/AdminAbout/Index.cshtml
@model ArchiNestCoreMVCProject.Entities.About
@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/AdminLayout/Index.cshtml";
}

<div class="col-lg-12 grid-margin stretch-card">
	<div class="card">
		<div class="card-body">
			<h4 class="card-title">About</h4>
			<div class="table-responsive">
				<table class="table table-striped table-hover">
					<thead>
						<tr>
							<th>#</th>
							<th>Title</th>
							<th>Description</th>
							<th>Subdescription</th>
							<th>Image URL</th>
							<th>Video URL</th>
							<th>Operations</th>
						</tr>
					</thead>
					<tbody>

						<tr>
							<td>@Model.AboutId</td>
							<td>@Model.Title</td>
							<td>@Model.Description1.Substring(0, 20)...</td>
							<td>@Model.Description2.Substring(0, 20)...</td>
							<td align="center"><img src="@Model.ImageUrl" style="height:61px; width:69px;" /></td>
							<td><a href="@Model.VideoUrl"> <i class="mdi mdi-play" style="width: 40px;"></i></a></td>
							<td>
								<a type="button" class="btn btn-inverse-primary btn-fw" href="/AdminAbout/Update/@Model.AboutId">Update</a>
								&nbsp;
								<a type="button" class="btn btn-inverse-danger btn-fw" href="/AdminAbout/Delete/@Model.AboutId">Delete</a>
							</td>
						</tr>


					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

ArchiNestCoreMVCProject/Views/AdminAbout/Update.cshtml
@model ArchiNestCoreMVCProject.Entities.About
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/AdminLayout/Index.cshtml";
}

<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update About Page</h4>
            <form class="forms-sample" method="post" asp-action="Update" asp-controller="AdminAbout">

                <input type="hidden" asp-for="AboutId" class="form-control" />

                <div class="form-group">
                    <label>Title</label>
                    <input type="text" class="form-control" placeholder="Title" asp-for="Title">
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <input type="text" class="form-control" placeholder="Short Description" asp-for="Description1">
                </div>

                <div class="form-group">
                    <label>Subdescription</label>
                    <input type="text" class="form-control" placeholder="Full Description" asp-for="Description2">
                </div>

                <div class="form-group">
                    <label>Image URL</label>
                    <input type="text" class="form-control" placeholder="Image URL" asp-for="ImageUrl">
                </div>

                <div class="form-group">
                    <label>Video URL</label>
                    <input type="text" class="form-control" placeholder="Video URL" asp-for="VideoUrl">
                </div>

                <button type="submit" class="btn btn-primary me-2">Update</button>
            </form>
        </div>
    </div>
</div>